on:
  release:
    types:
      - published

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  publish:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
